reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy
  resources :posts, except: :index do
    resources :comments, only: :new
  end
  resources :comments, only: [:create, :show]

end

reddit/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint           not null, primary key
#  content           :string           not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ApplicationRecord
    validates :content, presence: true

    belongs_to :author,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :User

    belongs_to :post,
        primary_key: :id,
        foreign_key: :post_id,
        class_name: :Post
    
    belongs_to :parent_comment,
        primary_key: :id,
        foreign_key: :parent_comment_id,
        class_name: :Comment,
        optional: true

    has_many :child_comments,
        primary_key: :id,
        foreign_key: :parent_comment_id,
        class_name: :Comment,
        inverse_of: :parent_comment

end

reddit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @comment = Comment.new
        render :new
    end

    def create
        @comment = Comment.new(comment_params)
        @comment.author_id = current_user.id
        @comment.post_id = params[:comment][:post_id]
        if @comment.save
            if @comment.parent_comment_id.nil?
                redirect_to post_url(params[:comment][:post_id])
            else
                redirect_to comment_url(@comment.parent_comment_id)
            end
        else
            flash.now[:errors] = @comment.errors.full_messages
            render :new
        end
    end

    def show
        @comment = Comment.find(params[:id])
        render :show
    end

    private
    def comment_params
        params.require(:comment).permit(:content, :parent_comment_id)
    end



end

reddit/app/views/comments/new.html.erb
<h1>New Comment</h1>

<form action='<%= comments_url %>' method='POST'>
    <%= auth_token %>
    <input type='hidden' name='comment[post_id]' value='<%= params[:post_id] %>'>
    
    <label for='content'>Content: </label>
    <input type='textarea' id='content' name='comment[content]' value='<%= @comment.content %>'>

    <input type='submit' value='Create New Comment'>

</form>

reddit/app/views/comments/show.html.erb
<h1>Parent Comment</h1>
<%= @comment.content %>

<h1>Nested Comments</h1>
<ul>
    <% @comment.child_comments.each do |comment| %>
        <li><%= comment.content %></li>
    <% end %>
</ul>

<form action="<%= comments_url %>" method="POST">
    <%= auth_token %>

    <input type='hidden' name='comment[parent_comment_id]' value="<%= @comment.id %>">
    <input type='hidden' name='comment[post_id]' value="<%= @comment.post_id %>">


    <label>New Comment: <input type="text" name="comment[content]"></label>

    <input type='submit' value='Add Comment'>
</form>

<a href='<%= subs_url %>'>Back to Subs</a>