reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy
  resources :posts, except: :index do
    resources :comments, only: :new
  end
  resources :comments, only: [:create, :show]

end

reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord

    validates :title, :description, presence: true

    belongs_to :moderator,
        primary_key: :id,
        foreign_key: :moderator_id,
        class_name: 'User'

    has_many :postsubs,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: 'PostSub',
        inverse_of: :sub 

    has_many :posts,
        through: :postsubs,
        source: :post

end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :ensure_moderator, only: [:edit, :update]

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def index
        @subs = Sub.all
        render :index
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def edit
        @sub = Sub.find(params[:id])
        render :edit
    end

    def update
        @sub = Sub.find(params[:id])
        if @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description)
    end

    def ensure_moderator
        redirect_to subs_url unless current_user.id == Sub.find(params[:id]).moderator_id
    end
end

reddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="POST">

    <%= auth_token %>
    <input type='hidden' name='_method' value='PATCH'>

    <label for='title'>Title: </label>
    <input type='text' id='title' name='sub[title]' value="<%= @sub.title %>">

    <label for='description'>Description: </label>
    <input type='text' id='description' name='sub[description]' value="<%= @sub.description %>">

    <input type="submit" value="Edit Sub">

</form>

reddit/app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
<% @subs.each do |sub| %>
    <li>
    <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
    </li>
<% end %>
</ul>

<a href="<%= new_sub_url %>">Add a Sub</a>

reddit/app/views/subs/new.html.erb
<h1>Add Sub</h1>

<form action="<%= subs_url %>" method="POST">

    <%= auth_token %>

    <label for='title'>Title: </label>
    <input type='text' id='title' name='sub[title]' value="<%= @sub.title %>">

    <label for='description'>Description: </label>
    <input type='text' id='description' name='sub[description]' value="<%= @sub.description %>">

    <input type="submit" value="Create New Sub">

</form>

reddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h2><%= @sub.description %></h2>
<h3>Moderator: <%= @sub.moderator.username %></h3>

<a href="<%= subs_url %>">Back to All Subs</a>
<br>
<% if @sub.moderator_id == current_user.id %>
    <a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
<% end%>

<h2>Posts</h2>

<ul>
    <% @sub.posts.each do |post| %>
        <li><a href='<%= post_url(post) %>'><%= post.title %></a></li>
    <% end%>
</ul>

<a href="<%= new_post_url %>">New Post</a>