reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy
  resources :posts, except: :index do
    resources :comments, only: :new
  end
  resources :comments, only: [:create, :show]

end

reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord

    validates :title, presence: true

    has_many :postsubs,
        primary_key: :id,
        foreign_key: :post_id,
        class_name: 'PostSub',
        inverse_of: :post 

    belongs_to :author,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: 'User'

    has_many :subs,
        through: :postsubs,
        source: :sub

    has_many :comments,
        primary_key: :id,
        foreign_key: :post_id,
        class_name: 'Comment'
        
end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :ensure_author, only: [:edit, :update]

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id
        if @post.save
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
        render :edit
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :edit
        end
    end

    def show
        @post = Post.find(params[:id])
        render :show
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy!
        redirect_to sub_url(@post.sub)
    end

    private
    def post_params
        params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end

    def ensure_author
        redirect_to subs_url unless current_user.id == Post.find(params[:id]).author_id
    end

end

reddit/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action='<%= post_url(@post) %>' method='POST'>
    <%= auth_token %>
    <input type='hidden' name='_method' value='PATCH'>
    <label for='title'>Title: </label>
    <input type='text' id='title' name='post[title]' value='<%= @post.title %>'>

    <label for='url'>URL: </label>
    <input type='text' id='url' name='post[url]' value='<%= @post.url %>'>
    
    <label for='content'>Content: </label>
    <input type='textarea' id='content' name='post[content]' value='<%= @post.content %>'>

    <input type='hidden' name='post[sub_ids][]' value="">

    <% Sub.all.each do |sub| %>
        <label for='sub_id'>
            <input  id='sub_id'
                    type='checkbox'
                    name='post[sub_ids][]'
                    value='<%= sub.id %>'
                    <%= "checked" if @post.sub_ids.include?(sub.id) %>>
            <%= sub.title %>
        </label>
    <% end %>

    <input type='submit' value='Edit Post'>

</form>

reddit/app/views/posts/new.html.erb
<h1>New Post</h1>

<form action='<%= posts_url %>' method='POST'>
    <%= auth_token %>

    <label for='title'>Title: </label>
    <input type='text' id='title' name='post[title]' value='<%= @post.title %>'>

    <label for='url'>URL: </label>
    <input type='text' id='url' name='post[url]' value='<%= @post.url %>'>
    
    <label for='content'>Content: </label>
    <input type='textarea' id='content' name='post[content]' value='<%= @post.content %>'>

    <input type='hidden' name='post[sub_ids][]' value="">

    <% Sub.all.each do |sub| %>
        <label for='sub_id'>
            <input  id='sub_id'
                    type='checkbox'
                    name='post[sub_ids][]'
                    value='<%= sub.id %>'
                    <%= "checked" if @post.sub_ids.include?(sub.id) %>>
            <%= sub.title %>
        </label>
    <% end %>

    <input type='submit' value='Create New Post'>

</form>

reddit/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2><%= @post.url %></h2>
<h2><%= @post.content %></h2>
<h3>Author: <%= @post.author.username %></h3>

<a href="<%= subs_url %>">Back to All Subs</a>
<br>
<a href="<%= edit_post_url(@post) %>">Edit Post</a>
<br>
<a href="<%= new_post_comment_url(@post) %>">Add Comment</a>

<h2>Comments</h2>

<ul>
    <% @post.comments.where(parent_comment_id: nil).each do |comment| %>
        <li>
            <a href="<%= comment_url(comment) %>"><%= comment.content %></a>
            <br>
            <ul>
                <% comment.child_comments.each do |child_comment|%>
                    <li><%= child_comment.content%></li>
                <% end%>
            </ul>       
        </li>
    <% end %>
</ul>